version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: catalagoFilme
      POSTGRES_USER: catalagoFilmeADA
      POSTGRES_PASSWORD: catalagoFilmeADA
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts/initial.sql:/docker-entrypoint-initdb.d/1-init.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
